scenario:
  defaults:
    scenario_path: lunettes/tests/login.yaml
    scenario_dir: lunettes/tests
    output_dir: temp/testfiles

  video:
    wait_between_steps: 0
    scroll_delay_ms: 35
    autoscroll_smooth: false
    resolution:
      width: 1280
      height: 720

      
  tts:    
    - profile: all-channels

      channels:
        purpose:
          enabled: true
          prefix: "Einleitung:"
        explanation:
          enabled: true
          prefix: "Erläuterung:"
        warning:
          enabled: true
          prefix: "Hinweis:"
        consequence:
          enabled: false
          prefix: "Auswirkung:"
        business_context:
          enabled: false
          prefix: "Fachlicher Hintergrund:"

      timing:
        before_step:
          - purpose
          - warning
        during_step:
          - explanation
        after_step:
          - consequence

      pauses:
        between_channels_ms: 200
        before_action_ms: 300
        after_action_ms: 300